### ISSUE TITLE
Update 3.0.x binaries to 3.0.0

### ISSUE THREAD

**Issue by thesamet** [os72/protoc-jar#10]

**Comment by os72** [comment]
Darn, I just released beta4..

**Comment by ilya-medvedev** [comment]
Link to artifacts: http://repo1.maven.org/maven2/com/google/protobuf/protoc/3.0.0/
From page: https://github.com/google/protobuf

**Comment by os72** [comment]
Ack

**Comment by os72** [comment]
Released 3.0.0
