### ISSUE TITLE
Protobuf 3.2.0

### ISSUE THREAD

**Issue by pradyuman** [os72/protoc-jar#17]
Protobuf 3.2.0 has been released: https://github.com/google/protobuf/releases/tag/v3.2.0
Is it possible to add a bin_320 for it? This will allow scalapb to update to protobuf 3.2.0 as well.

**Comment by os72** [comment]
Yes. In the meantime could you try the new `-v:<group>:<artifact>:<version>` option? It should download the binary from maven central. Please let me know if it works

`java -jar protoc-jar-3.1.0.3.jar -v:com.google.protobuf:protoc:3.2.0`

**Comment by pradyuman** [comment]
Is there an easy way to do this from sbt? I'm not using protoc-jar directly.

**Comment by os72** [comment]
How do you specify the version there? Instead of `-v3.1.0`, try `-v:com.google.protobuf:protoc:3.2.0`

**Comment by os72** [comment]
Try PB.protocVersion := "-v:com.google.protobuf:protoc:3.2.0"
(This should work with protoc-jar 3.1.0.3, until I release a 3.2.0 version)

See https://scalapb.github.io/sbt-settings.html

By default, sbt-protoc invokes protoc 3.0.0 that is shipped with protoc-jar. If you would like to run a different version of protoc:
PB.protocVersion := "-v261"

**Comment by os72** [comment]
Released 3.2.0

**Comment by pradyuman** [comment]
Sorry, I had some other stuff come up and couldn't test this out. Is this still something you need feedback for?

**Comment by os72** [comment]
Yes, I'd still be curious to confirm this works, thanks: `PB.protocVersion := "-v:com.google.protobuf:protoc:3.2.0"`

**Comment by pradyuman** [comment]
I tried with: `PB.protocVersion := "-v:com.google.protobuf:protoc:3.2.0"` and I got the error: `Unknown flag: -v`. This same error occurs with `PB.protocVersion := "-vcom.google.protobuf:protoc:3.2.0"`

I also tried with: `PB.protocVersion := "com.google.protobuf:protoc:3.2.0"` and get the error: `com.google.protobuf:protoc:3.2.0: No such file or directory`

**Comment by os72** [comment]
Ok thanks. It should work according to sbt documentation, see link (`-v` should be passed to protoc-jar). Check with them perhaps?
https://scalapb.github.io/sbt-settings.html

**Comment by cvogt** [comment]
related to https://github.com/os72/protoc-jar/issues/19
