### ISSUE TITLE
better error message for incorrect version

### ISSUE THREAD

**Issue by cvogt** [os72/protoc-jar#19]
Currently when you provide an invalid version to `runProtoc`, e.g. -v311, the error message you get is `Unknown flag: -v`, which is confusing. Better would be `Invalid version -v311. Available versions: -v320, -v310, -v261, ...`

**Comment by os72** [comment]
Ack

**Comment by os72** [comment]
Released 3.2.0.1

**Comment by cvogt** [comment]
nice :)! thx
