### ISSUE TITLE
Please add protoc 3.0.0-alpha-2

### ISSUE THREAD

**Issue by thesamet** [os72/protoc-jar#2]
Will it be possible to add this release as well? I would like to use it with ScalaPB (https://github.com/trueaccord/ScalaPB) for our next release which is going to add support proto3.

**Comment by os72** [comment]
Yes will look into it, need to sort out my VMs. What platform(s) do you use?

**Comment by thesamet** [comment]
I can help with building on Mac & Linux. There is an official Win32 build available in https://github.com/google/protobuf/releases

**Comment by os72** [comment]
I finally got to this, do you mind trying out the SNAPSHOT?

**Comment by thesamet** [comment]
@os72 Can't find where the SNAPSHOT is available to try, or should I build it myself?

**Comment by os72** [comment]
Yes I meant build yourself, just clone + maven clean install. If it works I can publish a release

**Comment by thesamet** [comment]
Works perfectly - tested on Linux. If it's not too hard 3.0.0-alpha-3 is already out and it would be great to upgrade to it.

I had to add this to the plugin section in pom.xml, otherwise it'd complain about generics not being available in Java 1.3:

            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.0</version>
            <configuration>
                <source>1.5</source>
                <target>1.5</target>
            </configuration>
        </plugin>

**Comment by os72** [comment]
Ok let me do the alpha3

**Comment by os72** [comment]
BTW do you have a way to test Mac too? I'm more worried abt that since I switched build VM

**Comment by thesamet** [comment]
Yes, I'll update.

On Tue, Jun 2, 2015 at 6:45 PM, os72 <notifications@github.com> wrote:

> BTW do you have a way to test Mac too? I'm more worried abt that since I
> switched build VM
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/os72/protoc-jar/issues/2#issuecomment-108156958>.
>



-- 
-Nadav

**Comment by os72** [comment]
BTW just pushed 3.0.0-alpha-3 binaries

**Comment by thesamet** [comment]
3.0.0-alpha3 works like a charm - both on Mac OS X and Linux.

**Comment by os72** [comment]
Great, I'll make the release soon

**Comment by os72** [comment]
Released version 3.0.0-a3
