### ISSUE TITLE
FreeBSD support?

### ISSUE THREAD

**Issue by GuyIncognito1986** [os72/protoc-jar#25]
Hey currently the protoc-jar throws "protoc-jar: protoc version: 330, detected platform: freebsd/amd64
java.lang.RuntimeException: error occurred while compiling protobuf files: Unsupported platform: freebsd/amd64", would it be difficult to add in freebsd support? protoc does exist and has been ported to freebsd, I'd be willing to help with the testing or the coding for the support, it should be trivial considering linux and mac osx are already supported.

**Comment by os72** [comment]
Sorry, I missed this.. Would you be able to provide binaries?

**Comment by GuyIncognito1986** [comment]
Yeah sure, I have freebsd 11 x64 binaries compiled for libressl, it took a while to get the tool chain/build working though, is that good enough?

**Comment by GuyIncognito1986** [comment]
Oh sorry just realised this isnt the grpc thread, yeah sure thing I can extract the protoc binaries for you, where would you like me to send them?

**Comment by os72** [comment]
You could create a new folder for your platform, and send a PR. protoc should be built statically (`./configure --disable-shared`,  `make install-strip`)

**Comment by os72** [comment]
You can use PRs #27, #28 as examples

**Comment by nakul02** [comment]
[Here](https://issues.apache.org/jira/browse/SYSTEMML-1875?focusedCommentId=16149507&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16149507) are more detailed instructions to compile the protobuf compiler.

**Comment by GuyIncognito1986** [comment]
Sorry dude, been busy starting a new contract, I will sort it out over over
the weekend. Tbh binary packages for protoc exist for freebsd, I should be
able to just extract those.

**Comment by kjopek** [comment]
Was done in #30 for FreeBSD 11.1.

**Comment by os72** [comment]
Released protoc-jar-3.4.0.1, protoc-jar-maven-plugin-3.4.0.1

**Comment by iphydf** [comment]
https://mvnrepository.com/artifact/com.github.os72/protoc-jar/3.4.0.1 does not include FreeBSD binaries. Where are they?

**Comment by os72** [comment]
Not all binaries are bundled (in order to keep the size manageable). But protoc-jar will automatically download:
http://central.maven.org/maven2/com/github/os72/protoc/
FreeBSD is there
