### ISSUE TITLE
Statically link linux binaries

### ISSUE THREAD

**Issue by utdemir** [os72/protoc-jar#26]
Hey.

I'm using `scalapb`, which transitively depends on this project for compiling `.proto` files on compile time.

However, I'm using NixOS (a Linux distribution) as operating system and the libraries are not on quite expected places. So the binaries provided with this library fail to start. If this library provided statically linked binaries, I wouldn't have this problem. 

I'm fine with statically compiled binaries for glibc, but if you use another `libc` implementation like `musl`, it'll work fine in both my environment and any other Linux distributions, which will also fix #15 .

**Comment by os72** [comment]
I'm afraid they're already as static as possible, both my builds and from Google. What version are you using? What platform does it print for you?

**Comment by utdemir** [comment]
I think I'm using `bin_330/linux` file. And here is what's going on:

```
$ uname -a
Linux galactica 4.9.41 #1-NixOS SMP Mon Aug 7 02:00:06 UTC 2017 x86_64 GNU/Linux
$ cd protoc-jar/bin_330_linux
$ file protoc 
protoc: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, BuildID[sha1]=a026b8d7a679fb21d4639fdd223ad306067d969b, stripped
$ ldd protoc 
/home/utdemir/.nix-profile/bin/ldd: line 117: ./protoc: No such file or directory
$ ls /lib64
ls: cannot access '/lib64': No such file or directory
```

**Comment by os72** [comment]
I meant, what does protoc-jar print as detected platform? (I wonder if we can even detect the difference) The 3.3.0 binary is the official build from Google BTW

**Comment by volth** [comment]
Discussion on NixOS forum
https://discourse.nixos.org/t/runtime-alternative-to-patchelf-set-interpreter/3539

**Comment by lorenzleutgeb** [comment]
Another workaround for this problem: Detect installation of NixOS by checking existence of `/nix`, and set `<protocCommand>` in that case. All Nix/NixOS users will have to install `protobuf` while others can enjoy the automatic JAR download. I know it's not pretty.

```xml
<project>
  <profiles>
    <profile>
      <id>protoc-command</id>
      <activation>
        <file>
          <exists>/nix</exists>
        </file>
      </activation>
      <build>
        <plugins>
          <plugin>
            <groupId>com.github.os72</groupId>
            <artifactId>protoc-jar-maven-plugin</artifactId>
            <executions>
              <execution>
                <configuration>
                  <protocCommand>protoc</protocCommand>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
```
