### ISSUE TITLE
protoc-jar issues

### ISSUE THREAD

**Issue by xlsong19** [os72/protoc-jar#29]
`[INFO]     Processing (java): op_def.proto
protoc-jar: executing: [/tmp/protocjar1578476083492466494/bin/protoc.exe, -I/tmp/protocjar1578476083492466494/include, -I/home/sxl/tools/TensorFlowOnYARN/tensorflow-parent/tensorflow-native/tensorflow, -I/home/sxl/tools/TensorFlowOnYARN/tensorflow-parent/tensorflow-native/tensorflow/tensorflow/core/framework, --java_out=/home/sxl/tools/TensorFlowOnYARN/tensorflow-parent/tensorflow-bridge/target/generated-sources/java, /home/sxl/tools/TensorFlowOnYARN/tensorflow-parent/tensorflow-native/tensorflow/tensorflow/core/framework/op_def.proto]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] TensorFlowOnYARN ................................... SUCCESS [  0.019 s]
[INFO] JNI bridge to TensorFlow ........................... FAILURE [  1.469 s]
[INFO] TensorFlow source codes ............................ SKIPPED
[INFO] TensorFlow on YARN Application ..................... SKIPPED
[INFO] TensorFlow on YARN Distribution .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.758 s
[INFO] Finished at: 2017-09-14T10:19:45+08:00
[INFO] Final Memory: 10M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.os72:protoc-jar-maven-plugin:3.2.0:run (default) on project tensorflow-bridge: protoc-jar failed for /home/sxl/tools/TensorFlowOnYARN/tensorflow-parent/tensorflow-native/tensorflow/tensorflow/core/framework/op_def.proto. Exit code 126 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.os72:protoc-jar-maven-plugin:3.2.0:run (default) on project tensorflow-bridge: protoc-jar failed for /home/sxl/tools/TensorFlowOnYARN/tensorflow-parent/tensorflow-native/tensorflow/tensorflow/core/framework/op_def.proto. Exit code 126`
I need protoc-jar on redflag7 ppc64le system. This is the error information . Then I find your project。Is there the proper protoc-jar for use. How I can use your pro.I try to build your project with mvn package command and the failure information is :`protoc-jar: protoc version: 340, detected platform: linux/ppc64le
protoc-jar: executing: [/tmp/protocjar2356743338703252815/bin/protoc.exe, --version]
/tmp/protocjar8131703302511454868/bin/protoc.exe: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/protocjar8131703302511454868/bin/protoc.exe)
/tmp/protocjar8131703302511454868/bin/protoc.exe: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/protocjar8131703302511454868/bin/protoc.exe)
protoc-jar: protoc version: 241, detected platform: linux/ppc64le
/tmp/protocjar2356743338703252815/bin/protoc.exe: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/protocjar2356743338703252815/bin/protoc.exe)
/tmp/protocjar2356743338703252815/bin/protoc.exe: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /tmp/protocjar2356743338703252815/bin/protoc.exe)
/tmp/protocjar2356743338703252815/bin/protoc.exe: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/protocjar2356743338703252815/bin/protoc.exe)
protoc-jar: executing: [/tmp/protocjar4720590836785863415/bin/protoc.exe, --java_out=target/test-protoc-shaded-241, src/test/resources/PersonSchema.proto]
protoc-jar: shading (version 241): target/test-protoc-shaded-241
/tmp/protocjar4720590836785863415/bin/protoc.exe: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /tmp/protocjar4720590836785863415/bin/protoc.exe)
/tmp/protocjar4720590836785863415/bin/protoc.exe: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /tmp/protocjar4720590836785863415/bin/protoc.exe)
protoc-jar: protoc version: com.google.protobuf:protoc:3.0.0, detected platform: linux/ppc64le
protoc-jar: downloading: http://central.maven.org/maven2/com/google/protobuf/protoc/3.0.0/protoc-3.0.0-linux-ppcle_64.exe
protoc-jar: protoc version: com.google.protobuf:protoc:3.0.0, detected platform: linux/ppc64le
protoc-jar: downloading: http://central.maven.org/maven2/com/google/protobuf/protoc/3.0.0/protoc-3.0.0-linux-ppcle_64.exe
protoc-jar: protoc version: 261, detected platform: linux/ppc64le
protoc-jar: executing: [/tmp/protocjar4920792793957725484/bin/protoc.exe, -I/tmp/protocjar4920792793957725484/include, -I., --java_out=target/test-protoc-stdtypes, src/test/resources/StdTypeExample2.proto]
Tests run: 5, Failures: 4, Errors: 1, Skipped: 0, Time elapsed: 1.302 sec <<< FAILURE!
testRunProtocCompile(com.github.os72.protocjar.ProtocTest)  Time elapsed: 0.147 sec  <<< FAILURE!`
How can I solve my problem?Hope your reply!

**Comment by os72** [comment]
Are you able to run `java -jar protoc-jar-3.4.0.jar --version`
