### ISSUE TITLE
protoc name does not correspond with detected platform

### ISSUE THREAD

**Issue by ahjohannessen** [os72/protoc-jar#3]
Would it be possible to set correct name for the `protoc` executable depending on detected platform?

https://github.com/os72/protoc-jar/blob/master/src/main/java/com/github/os72/protocjar/Protoc.java#L103

**Comment by ahjohannessen** [comment]
I get this:
```
protoc-jar: protoc version: 261, detected platform: mac os x/x86_64
protoc-jar: executing: [/var/folders/y5/lswvltf14fx02nn9xhtv_65m0000gn/T/protoc4087409384165246742.exe, --plugin=protoc-gen-scala=...
```

**Comment by os72** [comment]
Is it for cosmetic or functional purpose?

**Comment by ahjohannessen** [comment]
Purely cosmetic and OCD :-)

**Comment by os72** [comment]
What would be the "correct" name for the temp protoc?

**Comment by ahjohannessen** [comment]
I reckon that `protocX` is "correct" for *nix based systems and `protocX.exe` for win where `X` is generated.

**Comment by os72** [comment]
createTempFile() asks for suffix hence .exe

**Comment by ahjohannessen** [comment]
`abcdx.protoc` and `abcdx.protoc.exe` - But really, this is just my nitpicking. Feel free to close this issue if you think this is a bit too much :)
