### ISSUE TITLE
protoc for arm64

### ISSUE THREAD

**Issue by garciagorka** [os72/protoc-jar#33]
Any chance of adding arm64 to the supported platforms? 
I am happy to provide the binaries if needed.

**Comment by os72** [comment]
Yes, of course, that would be great. Please make sure to build statically and strip the binaries

`./configure --disable-shared & make install-strip`

See also PRs #27, #31

**Comment by os72** [comment]
@garciagorka, your binaries are uploaded to SNAPSHOT repo
https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/

Following should work for you now on ARM platform:
`java -jar protoc-jar-3.4.0.1.jar --version -v2.4.1-SNAPSHOT`
`java -jar protoc-jar-3.4.0.1.jar --version -v2.6.1-SNAPSHOT`
`java -jar protoc-jar-3.4.0.1.jar --version -v3.4.0-SNAPSHOT`

Could you confirm?
Thanks

**Comment by garciagorka** [comment]
I confirm it is working on my ARM64 platform. 
Thanks

**Comment by os72** [comment]
ARM binaries are now included in build2 released to maven central
http://central.maven.org/maven2/com/github/os72/protoc/

And following should now detect and download release build2:
`java -jar protoc-jar-3.4.0.2.jar --version -v2.4.1`
`java -jar protoc-jar-3.4.0.2.jar --version -v2.6.1`
`java -jar protoc-jar-3.4.0.2.jar --version -v3.4.0`

**Comment by os72** [comment]
BTW protobuf 3.5.0 is out, Google has provided ARM64 binary this time
http://central.maven.org/maven2/com/google/protobuf/protoc/3.5.0/
