### ISSUE TITLE
protoc 3.5.0 on freebsd-x86_64

### ISSUE THREAD

**Issue by os72** [os72/protoc-jar#35]
Hi @kjopek
protobuf 3.5.0 is out, can we get protoc 3.5.0 binary on freebsd-x86_64?

**Comment by kjopek** [comment]
Give me 1h.

**Comment by kjopek** [comment]
#37 is ready.

**Comment by os72** [comment]
Thank you. 3.5.0 is released w freebsd-x86_64 support
