### ISSUE TITLE
Wrong protoc for FreeBSD

### ISSUE THREAD

**Issue by AlexanderShniperson** [os72/protoc-jar#46]
Hi

I'm trying to compile `proto` files with required version `v261` and looks like `protoc-jar` takes wrong version, here is messages
```
protoc-jar: protoc version: 2.6.1, detected platform: osx-x86_64 (mac os x/x86_64)
protoc-jar: embedded: bin/2.6.1/protoc-2.6.1-osx-x86_64.exe
```
As you can see i have Mac osx and protoc takes `exe` Windows executable version, but it should be binary executable FreeBSD based protoc

**Comment by os72** [comment]
I'm confused, what's your platform? Mac or BSD?
It seems to detect and run Mac executable
