### ISSUE TITLE
Incorrect Arch in Win 64

### ISSUE THREAD

**Issue by justinj656** [os72/protoc-jar#47]
Run `java -jar protoc-jar-3.5.1.1.jar -pp` in windows 7, 64 bit OS.
It shows the following result
![image](https://user-images.githubusercontent.com/6373811/41214077-d6679d24-6d7b-11e8-8360-4c984fdd5838.png)
System Info:
![image](https://user-images.githubusercontent.com/6373811/41214041-b04acd28-6d7b-11e8-9d35-ae774f6699bf.png)

Print `os.name`, `os.arch`, `os.version` in command prompt, and it shows
```
Windows 7
x86
6.1
```

Run `wmic os get osarchitecture`, and it shows
```
OSArchitecture
64-bit
```

According to https://github.com/os72/protoc-jar/blob/master/src/main/java/com/github/os72/protocjar/PlatformDetector.java#L187, it will be determined as 'win_32'.

Is this a common problem or just an exception in my env?

**Comment by os72** [comment]
Yes that's unusal. On my Win 7 machine it says:

```
$ java -jar protoc-jar-3.5.1.1.jar -pp
------------------------------------------------------------------------
Detecting the operating system and CPU architecture
------------------------------------------------------------------------
os.detected.name: windows
os.detected.arch: x86_64
os.detected.version: 6.1
os.detected.version.major: 6
os.detected.version.minor: 1
os.detected.classifier: windows-x86_64
```

Even so it may work, it will try downloading 32 bit exe
Does it not work?

**Comment by justinj656** [comment]
Sure, but it is a problem for v2.4.1.
Protoc v2.4.1 is no longer available in maven central.
http://central.maven.org/maven2/com/google/protobuf/protoc/
```xml
<versions>
  <version>2.5.0</version>
  <version>2.6.1</version>
  <version>2.6.1-build2</version>
  <version>3.0.0-alpha-2</version>
  <version>3.0.0-alpha-3</version>
  <version>3.0.0-alpha-3.1</version>
  <version>3.0.0-beta-1</version>
  <version>3.0.0-beta-2</version>
  <version>3.0.0-beta-3</version>
  <version>3.0.0-beta-4</version>
  <version>3.0.0</version>
  <version>3.0.2</version>
  <version>3.1.0</version>
  <version>3.1.0-build2</version>
  <version>3.2.0-rc.1</version>
  <version>3.2.0rc2</version>
  <version>3.2.0</version>
  <version>3.3.0</version>
  <version>3.4.0</version>
  <version>3.5.0</version>
  <version>3.5.1</version>
  <version>3.5.1-1</version>
  <version>3.6.0</version>
</versions>
```

**Comment by os72** [comment]
Is it possible you're running a 32 bit JVM?
https://groups.google.com/forum/#!topic/ooo-libs/mqXkYAg3YCw

**Comment by os72** [comment]
Assuming closed
