### ISSUE TITLE
Allow capturing stdout/stderr

### ISSUE THREAD

**Issue by raboof** [os72/protoc-jar#48]
Currently Protoc output is send to stdout/stderr:

https://github.com/os72/protoc-jar/blob/7d8175051588aa870996ec79c246204299988fe3/src/main/java/com/github/os72/protocjar/Protoc.java#L125-L126

It would be nice to expose this to allow the calling process to capture the output.

**Comment by os72** [comment]
Ack. Something like `Protoc.runProtoc(String[] args, OutputStream out, OutputStream err)`?

**Comment by os72** [comment]
Released protoc-jar 3.6.0
