### ISSUE TITLE
[security] Download mechanism compromiseable.

### ISSUE THREAD

**Issue by bmhm** [os72/protoc-jar#55]
Hi,

for one, your download mechanism doesn't use maven mechanisms. This means: No https, no checking of checksums or digital signatures. After download, the file could have been altered before execution. You don't do any checking, as far as I can tell.

On the other hand I'd like to be able to use my local proxying / mirroring repository.
With a hardcoded URL this is just not possible:
https://github.com/os72/protoc-jar/blob/master/src/main/java/com/github/os72/protocjar/Protoc.java#L271

I think it would be a wise idea to use the maven API to download artifacts. Can this be done?

**Comment by os72** [comment]
I guess it could be done, not sure how much effort. Could you prototype it?

**Comment by os72** [comment]
Re proxying, it's built-in:
https://docs.oracle.com/javase/7/docs/api/java/net/doc-files/net-properties.html#Proxies

Re local mirror, we could add an override (cmd line or property, downloadUrl or something)

Would that work for your environment?

**Comment by os72** [comment]
Well, part of the question was about proxy. I guess download URL override could be an enhancement

Note that `protoc-jar` is independent of maven APIs. Which doesn't mean it cannot be improved as suggested (as an option)

**Comment by os72** [comment]
@bmhm, are you using maven mirror or proxy? settings.xml would be useful
https://maven.apache.org/guides/mini/guide-mirror-settings.html
(See issue #57)

Could you try building this branch
https://github.com/os72/protoc-jar/tree/support_mirror

And run
`java -jar protoc-jar-3.7.0.1-SNAPSHOT.jar --version -v351`

Thanks

**Comment by os72** [comment]
Closing, see #57
