### ISSUE TITLE
Support download from maven central mirror

### ISSUE THREAD

**Issue by os72** [os72/protoc-jar#57]
Support download from maven central mirror

From https://github.com/os72/protoc-jar-maven-plugin/issues/61
Part of issue #55

**Comment by gkumar7** [comment]
@os72 for now, could the url used to download protoc be updated to use https://repo.maven.apache.org/maven2/

I have made the change locally and Protoc still seems to work as expected.

**Comment by os72** [comment]
Ack, yes

**Comment by gkumar7** [comment]
@os72, could this change be included in 3.7.0 release? Many thanks!

**Comment by os72** [comment]
https://maven.apache.org/guides/mini/guide-mirror-settings.html

**Comment by os72** [comment]
See also https://github.com/os72/protoc-jar-maven-plugin/issues/68

**Comment by os72** [comment]
Released 3.7.0.1
