### ISSUE TITLE
Release for protobuf 3.7.1

### ISSUE THREAD

**Issue by tsabran** [os72/protoc-jar#66]
Hi,
Protobuf 3.7.0 had a few regressions which have been fixed in 3.7.1.
https://github.com/protocolbuffers/protobuf/releases/tag/v3.7.1
https://repo.maven.apache.org/maven2/com/google/protobuf/protoc/3.7.1/

In particular some builds are broken with 3.7.0 on some systems due to an unnecessary dependency on libatomic.

**Comment by os72** [comment]
Ack. Note protoc-jar will attempt to download if the version isn't found embedded, this may help in the meantime

**Comment by emempi** [comment]
Note that although this helps with local development, running this in temporary build envs with transient /tmp this generates a lot of request to https://repo.maven.apache.org .

**Comment by os72** [comment]
Released protoc-jar 3.7.1
