### ISSUE TITLE
Protoc download fails if mirror URL does not end in a '/'

### ISSUE THREAD

**Issue by grollinger** [os72/protoc-jar#67]
This [line](https://github.com/os72/protoc-jar/blob/ed71cba81c36023c23c1a18ecd060de8ee917b88/src/main/java/com/github/os72/protocjar/MavenUtil.java#L44) just concatenates the mirror URL onto the path of the artifact without any checking. 

If the mirror URL does not end in a '/' this will do the wrong thing.

Might I suggest using the Java support for [URIs](https://docs.oracle.com/javase/7/docs/api/java/net/URI.html) instead of working with strings directly?

**Comment by os72** [comment]
Ack. Would you be interested in submitting a PR?

**Comment by os72** [comment]
Released protoc-jar 3.7.1
