### ISSUE TITLE
Is there any way to include comments in the generated .proto file?

### ISSUE THREAD

**Issue by mike-ruane** [os72/protoc-jar#76]
In google's descriptor code, there's a [SourceCodeInfo message](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/descriptor.proto#L730) that contains a Location message that has access to the comments on fields. Is there anyway we can expose this in the generated proto file?

**Comment by os72** [comment]
Maybe via protoc `--include_source_info` option?

**Comment by mike-ruane** [comment]
Yes I actually figured that out shortly after raising the issue... I mean to close it but forgot! Apologies, and thanks for getting back to me!
